#!/usr/bin/env bash
## This script loops 1-10 and displays 3 iterations
Write a Bash script that loops from 1 to 10 and:

i=1
while [ $i -le 10 ] 
do
if [ $i == 4 ]
then
	echo "bad luck"
	((i++))
elif [ $i == 8 ]
then
	echo "good luck" 
	((i++))
else
echo "Best School"
	((i++))
fi

done
