#!/usr/bin/bash
## This script will display numbers and sentance iterations. 

x=0
while [ $x -le 20 ]
do echo {1..20}
   ((x++))
   case "$x" in
       5) echo "bad luck from China"
	  ;;
	  10) echo "bad luck from Japan"
	      ;;
	  18) echo "bad luck from Italy"
	      ;;
	  esac
   ((x++))
done
